python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_0_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_1_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_2_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_3_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_4_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_5_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_6_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_7_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_8_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_9_0.1_0.0"        --sim="boids"       --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_10_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_11_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_12_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_13_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_14_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_15_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_16_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_17_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_18_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_19_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_20_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_21_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_22_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_23_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_24_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_25_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_26_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_27_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_28_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_29_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_30_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_boids_31_0.1_0.0"       --sim="boids"       --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_0_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_1_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_2_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_3_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_4_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_5_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_6_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_7_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_8_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_9_0.1_0.0"         --sim="dnca"        --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_10_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_11_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_12_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_13_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_14_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_15_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_16_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_17_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_18_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_19_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_20_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_21_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_22_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_23_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_24_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_25_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_26_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_27_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_28_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_29_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_30_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_dnca_31_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_0_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_1_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_2_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_3_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_4_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_5_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_6_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_7_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_8_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_9_0.1_0.0"        --sim="lenia"       --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_10_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_11_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_12_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_13_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_14_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_15_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_16_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_17_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_18_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_19_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_20_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_21_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_22_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_23_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_24_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_25_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_26_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_27_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_28_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_29_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_30_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_lenia_31_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_0_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_1_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_2_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_3_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_4_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_5_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_6_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_7_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_8_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_9_0.1_0.0"       --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_10_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_11_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_12_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_13_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_14_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_15_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_16_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_17_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_18_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_19_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_20_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_21_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_22_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_23_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_24_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_25_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_26_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_27_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_28_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_29_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_30_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d1_31_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_0_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_1_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_2_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_3_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_4_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_5_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_6_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_7_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_8_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_9_0.1_0.0"       --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_10_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_11_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_12_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_13_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_14_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_15_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_16_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_17_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_18_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_19_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_20_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_21_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_22_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_23_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_24_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_25_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_26_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_27_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_28_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_29_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_30_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_nca_d3_31_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_0_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_1_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_2_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_3_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_4_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_5_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_6_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_7_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_8_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_9_0.1_0.0"       --sim="plenia"      --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_10_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_11_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_12_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_13_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_14_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_15_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_16_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_17_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_18_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_19_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_20_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_21_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_22_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_23_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_24_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_25_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_26_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_27_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_28_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_29_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_30_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plenia_31_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_0_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_1_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_2_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_3_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_4_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_5_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_6_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_7_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_8_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_9_0.1_0.0"      --sim="plife_a"     --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_10_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_11_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_12_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_13_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_14_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_15_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_16_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_17_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_18_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_19_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_20_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_21_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_22_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_23_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_24_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_25_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_26_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_27_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_28_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_29_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_30_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_a_31_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_0_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_1_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_2_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_3_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_4_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_5_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_6_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_7_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_8_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_9_0.1_0.0"     --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_10_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_11_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_12_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_13_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_14_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_15_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_16_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_17_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_18_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_19_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_20_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_21_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_22_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_23_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_24_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_25_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_26_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_27_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_28_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_29_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_30_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_31_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_0_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a biological cell under the microscope"     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_1_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a bacterium"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_2_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a diverse ecosystem of cells moving around" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_3_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="top down view of a colony of diverse cells" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_4_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a network of neurons"                       --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_5_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a multi-celled organism"                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_6_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a virus and fungal colony"                  --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_7_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="an artificial life organism"                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_8_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a red organism"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_9_0.1_0.0"  --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a green organism"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_10_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a blue organism"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_11_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a self-replicating pattern"                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_12_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="swarm intelligence"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_13_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a school of fish"                           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_14_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="the flocking behavior of birds"             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_15_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a trail of ants"                            --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_16_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature"               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_17_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="concentric circles"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_18_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a starfish"                                 --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_19_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a colorful striped snake"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_20_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a caterpillar"                              --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_21_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a butterfly"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_22_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a coral reef"                               --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_23_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a tree with roots"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_24_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a beautiful flower"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_25_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a snowflake"                                --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_26_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a fractal pattern"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_27_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a complex maze"                             --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_28_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a pepperoni pizza"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_29_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="the sun"                                    --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_30_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="an eye"                                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt/0_plife_ba_c3_31_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=1 --prompts="a galaxy"                                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
