python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_0_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_1_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_2_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_3_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_4_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_5_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_6_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_7_0.1_0.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_0_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_1_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_2_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_3_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_4_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_5_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_6_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_7_0.1_0.1"       --sim="boids"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_0_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_1_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_2_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_3_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_4_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_5_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_6_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_7_0.1_0.3"       --sim="boids"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_0_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_1_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_2_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_3_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_4_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_5_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_6_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_boids_7_0.1_1.0"       --sim="boids"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_0_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_1_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_2_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_3_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_4_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_5_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_6_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_7_0.1_0.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_0_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_1_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_2_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_3_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_4_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_5_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_6_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_7_0.1_0.1"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_0_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_1_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_2_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_3_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_4_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_5_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_6_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_7_0.1_0.3"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_0_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_1_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_2_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_3_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_4_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_5_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_6_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_dnca_7_0.1_1.0"        --sim="dnca"        --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_0_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_1_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_2_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_3_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_4_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_5_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_6_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_7_0.1_0.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_0_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_1_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_2_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_3_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_4_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_5_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_6_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_7_0.1_0.1"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_0_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_1_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_2_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_3_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_4_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_5_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_6_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_7_0.1_0.3"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_0_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_1_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_2_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_3_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_4_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_5_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_6_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_lenia_7_0.1_1.0"       --sim="lenia"       --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_0_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_1_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_2_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_3_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_4_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_5_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_6_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_7_0.1_0.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_0_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_1_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_2_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_3_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_4_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_5_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_6_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_7_0.1_0.1"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_0_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_1_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_2_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_3_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_4_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_5_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_6_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_7_0.1_0.3"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_0_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_1_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_2_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_3_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_4_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_5_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_6_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d1_7_0.1_1.0"      --sim="nca_d1"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_0_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_1_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_2_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_3_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_4_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_5_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_6_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_7_0.1_0.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_0_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_1_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_2_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_3_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_4_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_5_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_6_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_7_0.1_0.1"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_0_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_1_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_2_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_3_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_4_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_5_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_6_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_7_0.1_0.3"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_0_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_1_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_2_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_3_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_4_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_5_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_6_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_nca_d3_7_0.1_1.0"      --sim="nca_d3"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_0_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_1_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_2_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_3_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_4_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_5_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_6_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_7_0.1_0.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_0_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_1_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_2_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_3_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_4_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_5_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_6_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_7_0.1_0.1"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_0_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_1_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_2_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_3_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_4_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_5_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_6_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_7_0.1_0.3"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_0_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_1_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_2_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_3_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_4_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_5_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_6_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plenia_7_0.1_1.0"      --sim="plenia"      --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=1000 --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_0_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_1_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_2_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_3_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_4_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_5_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_6_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_7_0.1_0.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_0_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_1_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_2_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_3_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_4_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_5_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_6_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_7_0.1_0.1"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_0_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_1_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_2_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_3_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_4_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_5_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_6_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_7_0.1_0.3"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_0_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_1_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_2_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_3_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_4_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_5_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_6_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_a_7_0.1_1.0"     --sim="plife_a"     --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_0_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_1_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_2_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_3_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_4_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_5_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_6_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_7_0.1_0.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_0_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_1_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_2_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_3_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_4_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_5_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_6_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_7_0.1_0.1"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_0_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_1_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_2_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_3_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_4_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_5_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_6_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_7_0.1_0.3"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_0_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_1_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_2_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_3_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_4_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_5_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_6_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_7_0.1_1.0"    --sim="plife_ba"    --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_0_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_1_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_2_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_3_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_4_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_5_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_6_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_7_0.1_0.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_0_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_1_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_2_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_3_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_4_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_5_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_6_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_7_0.1_0.1" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.1 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_0_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_1_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_2_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_3_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_4_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_5_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_6_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_7_0.1_0.3" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=0.3 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_0_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a biological cell under the microscope" --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_1_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a network of neurons"                   --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_2_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a red organism"                         --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_3_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="swarm intelligence"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_4_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a fibonacci spiral in nature"           --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_5_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a caterpillar"                          --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_6_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a beautiful flower"                     --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
python main_opt.py --seed=0 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_oe/0_plife_ba_c3_7_0.1_1.0" --sim="plife_ba_c3" --n_rollout_imgs=4 --prompts="a pepperoni pizza"                      --coef_prompts=1.0 --coef_novelty=1.0 --bs=1 --pop_size=16 --n_iters=300  --sigma=0.1
