python main_opt.py --seed=0  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/0"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a biological cell,a biological cell"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=1  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/1"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a biological cell,a network of neurons"                    --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=2  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/2"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a biological cell,a virus and fungal colony"               --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=3  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/3"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a biological cell,a self-replicating pattern"              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=4  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/4"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a biological cell,a caterpillar"                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=5  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/5"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a biological cell,a pepperoni pizza"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=6  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/6"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a network of neurons,a biological cell"                    --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=7  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/7"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a network of neurons,a network of neurons"                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=8  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/8"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a network of neurons,a virus and fungal colony"            --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=9  --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/9"  --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a network of neurons,a self-replicating pattern"           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=10 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/10" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a network of neurons,a caterpillar"                        --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=11 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/11" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a network of neurons,a pepperoni pizza"                    --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=12 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/12" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a virus and fungal colony,a biological cell"               --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=13 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/13" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a virus and fungal colony,a network of neurons"            --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=14 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/14" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a virus and fungal colony,a virus and fungal colony"       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=15 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/15" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a virus and fungal colony,a self-replicating pattern"      --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=16 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/16" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a virus and fungal colony,a caterpillar"                   --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=17 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/17" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a virus and fungal colony,a pepperoni pizza"               --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=18 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/18" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a self-replicating pattern,a biological cell"              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=19 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/19" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a self-replicating pattern,a network of neurons"           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=20 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/20" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a self-replicating pattern,a virus and fungal colony"      --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=21 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/21" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a self-replicating pattern,a self-replicating pattern"     --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=22 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/22" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a self-replicating pattern,a caterpillar"                  --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=23 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/23" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a self-replicating pattern,a pepperoni pizza"              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=24 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/24" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a caterpillar,a biological cell"                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=25 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/25" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a caterpillar,a network of neurons"                        --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=26 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/26" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a caterpillar,a virus and fungal colony"                   --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=27 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/27" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a caterpillar,a self-replicating pattern"                  --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=28 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/28" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a caterpillar,a caterpillar"                               --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=29 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/29" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a caterpillar,a pepperoni pizza"                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=30 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/30" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a pepperoni pizza,a biological cell"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=31 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/31" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a pepperoni pizza,a network of neurons"                    --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=32 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/32" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a pepperoni pizza,a virus and fungal colony"               --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=33 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/33" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a pepperoni pizza,a self-replicating pattern"              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=34 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/34" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a pepperoni pizza,a caterpillar"                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=35 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/35" --sim="lenia_1.0" --n_rollout_imgs=1 --prompts="a pepperoni pizza,a pepperoni pizza"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=36 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/36" --sim="boids"     --n_rollout_imgs=1 --prompts="a biological cell,a biological cell"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=37 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/37" --sim="boids"     --n_rollout_imgs=1 --prompts="a biological cell,collective intelligence"                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=38 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/38" --sim="boids"     --n_rollout_imgs=1 --prompts="a biological cell,a fibonacci spiral in nature"            --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=39 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/39" --sim="boids"     --n_rollout_imgs=1 --prompts="a biological cell,a starfish"                              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=40 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/40" --sim="boids"     --n_rollout_imgs=1 --prompts="a biological cell,a snake"                                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=41 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/41" --sim="boids"     --n_rollout_imgs=1 --prompts="a biological cell,a tree with roots"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=42 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/42" --sim="boids"     --n_rollout_imgs=1 --prompts="collective intelligence,a biological cell"                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=43 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/43" --sim="boids"     --n_rollout_imgs=1 --prompts="collective intelligence,collective intelligence"           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=44 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/44" --sim="boids"     --n_rollout_imgs=1 --prompts="collective intelligence,a fibonacci spiral in nature"      --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=45 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/45" --sim="boids"     --n_rollout_imgs=1 --prompts="collective intelligence,a starfish"                        --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=46 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/46" --sim="boids"     --n_rollout_imgs=1 --prompts="collective intelligence,a snake"                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=47 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/47" --sim="boids"     --n_rollout_imgs=1 --prompts="collective intelligence,a tree with roots"                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=48 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/48" --sim="boids"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature,a biological cell"            --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=49 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/49" --sim="boids"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature,collective intelligence"      --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=50 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/50" --sim="boids"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature,a fibonacci spiral in nature" --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=51 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/51" --sim="boids"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature,a starfish"                   --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=52 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/52" --sim="boids"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature,a snake"                      --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=53 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/53" --sim="boids"     --n_rollout_imgs=1 --prompts="a fibonacci spiral in nature,a tree with roots"            --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=54 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/54" --sim="boids"     --n_rollout_imgs=1 --prompts="a starfish,a biological cell"                              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=55 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/55" --sim="boids"     --n_rollout_imgs=1 --prompts="a starfish,collective intelligence"                        --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=56 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/56" --sim="boids"     --n_rollout_imgs=1 --prompts="a starfish,a fibonacci spiral in nature"                   --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=57 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/57" --sim="boids"     --n_rollout_imgs=1 --prompts="a starfish,a starfish"                                     --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=58 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/58" --sim="boids"     --n_rollout_imgs=1 --prompts="a starfish,a snake"                                        --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=59 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/59" --sim="boids"     --n_rollout_imgs=1 --prompts="a starfish,a tree with roots"                              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=60 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/60" --sim="boids"     --n_rollout_imgs=1 --prompts="a snake,a biological cell"                                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=61 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/61" --sim="boids"     --n_rollout_imgs=1 --prompts="a snake,collective intelligence"                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=62 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/62" --sim="boids"     --n_rollout_imgs=1 --prompts="a snake,a fibonacci spiral in nature"                      --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=63 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/63" --sim="boids"     --n_rollout_imgs=1 --prompts="a snake,a starfish"                                        --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=64 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/64" --sim="boids"     --n_rollout_imgs=1 --prompts="a snake,a snake"                                           --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=65 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/65" --sim="boids"     --n_rollout_imgs=1 --prompts="a snake,a tree with roots"                                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=66 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/66" --sim="boids"     --n_rollout_imgs=1 --prompts="a tree with roots,a biological cell"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=67 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/67" --sim="boids"     --n_rollout_imgs=1 --prompts="a tree with roots,collective intelligence"                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=68 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/68" --sim="boids"     --n_rollout_imgs=1 --prompts="a tree with roots,a fibonacci spiral in nature"            --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=69 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/69" --sim="boids"     --n_rollout_imgs=1 --prompts="a tree with roots,a starfish"                              --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=70 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/70" --sim="boids"     --n_rollout_imgs=1 --prompts="a tree with roots,a snake"                                 --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
python main_opt.py --seed=71 --save_dir="/home/akarsh_sakana_ai/nca-alife-data/main_opt_temporal_lenia_boids/71" --sim="boids"     --n_rollout_imgs=1 --prompts="a tree with roots,a tree with roots"                       --coef_prompt=1.0 --coef_softmax=0.5 --coef_novelty=0.0 --bs=1 --pop_size=16 --n_iters=10000 --sigma=0.1
